let val1;
var array;
array=new Array();
array[1]="Enero";
array[2]="Febrero";
array[3]="Marzo";
array[4]="Abril";
array[5]="Mayo";
array[6]="Junio";
array[7]="Julio";
array[8]="Agosto";
array[9]="Septiembre";
array[10]="Octubre";
array[11]="Noviembre";
array[12]="Diembre";
let val2 = prompt("Introduce el primer numero", "0");
document.write(array[val2]);
